[alembic]
script_location = migrations
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
prepend_sys_path = .
sqlalchemy.url = mysql+pymysql://root:rootpassword@localhost:3306/socialpulse_ai

[post_write_hooks]

[logging]
default = INFO
