# tests/test_oauth_health.py
"""Unit test suite for GET /api/v1/oauth/health diagnostic endpoint."""

import pytest
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_get_oauth_health_endpoint():
    """Verify GET /api/v1/oauth/health returns structured status for all 8 providers."""
    response = client.get("/api/v1/oauth/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"
    assert "providers" in data
    
    providers = data["providers"]
    expected_keys = ["google", "github", "microsoft", "linkedin", "meta", "tiktok", "pinterest", "x"]
    for key in expected_keys:
        assert key in providers
        p = providers[key]
        assert "name" in p
        assert "status" in p
        assert "redirect_uri" in p
        assert p["status"] in ["READY", "MISSING_CREDENTIALS", "CONFIGURATION ERROR"]


def test_meta_oauth_scopes():
    """Ensure Meta OAuth URL generated by SocialGraphService uses requested Consumer permissions."""
    from app.services.social_graph_service import SocialGraphService
    import urllib.parse

    try:
        url = SocialGraphService.get_authorization_url("facebook", "http://localhost:3000/callback", "test_state")
        parsed = urllib.parse.urlparse(url)
        params = urllib.parse.parse_qs(parsed.query)
        scopes = params.get("scope", [""])[0].split(",")

        # Verify invalid scopes are not present
        assert "instagram_business_basic" not in scopes
        assert "instagram_business_manage_insights" not in scopes

        # Verify consumer permissions are present
        assert "public_profile" in scopes
        assert "email" in scopes
        assert "user_posts" in scopes
        assert "user_photos" in scopes
        assert "user_likes" in scopes
    except Exception as e:
        # If client_id is not set in env, check exception detail or pass if expected
        assert "META_APP_ID" in str(e) or "client_id" in str(e) or "Railway" in str(e) or "App ID" in str(e)

